version: "3.8"

services:
  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "8000:8000"
    environment:
      - TESTING=0
    # volumes:              # Uncomment these for live-reloading during development
    #   - ./todo-backend/app:/app/app
  
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # volumes:              # Uncomment these for live-reloading during development
    #   - ./todo-frontend:/todo-frontend